# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 01:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kbs_view', '0002_kbs_document_publisher'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='kbs_document',
            new_name='Document',
        ),
    ]
