# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 12:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kbs_view', '0005_auto_20170321_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='date_modified',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='publisher',
            field=models.CharField(default='Unknown User', max_length=50),
        ),
    ]
