# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-23 18:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kbs_view', '0007_files_upload_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='software_product',
            field=models.CharField(choices=[('BR', 'Brink'), ('PX', 'Pixel'), ('SV', 'Siva'), ('HR', 'Heritage')], default='BR', max_length=2),
        ),
    ]
