# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 16:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kbs_view', '0009_auto_20170327_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='title',
            field=models.CharField(max_length=128, unique=True, verbose_name='Document Title'),
        ),
    ]
