# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 16:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kbs_view', '0010_auto_20170327_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='favorited',
            field=models.BooleanField(default=False, editable=False, verbose_name='Favorited?'),
        ),
        migrations.AlterField(
            model_name='document',
            name='software_product',
            field=models.CharField(choices=[('BR', 'Brink'), ('PX', 'Pixel'), ('SV', 'Siva'), ('HR', 'Heritage')], default='BR', help_text='Select the software regarding this KBS Document', max_length=2, verbose_name='Software Product'),
        ),
        migrations.AlterField(
            model_name='document',
            name='views',
            field=models.IntegerField(default=0, editable=False, help_text='Number of times this document has been viewed.'),
        ),
    ]
