# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 04:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kbs_view', '0004_auto_20170321_2040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='files',
            name='image',
        ),
        migrations.AddField(
            model_name='document',
            name='favorited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='document',
            name='views',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='files',
            name='file',
            field=models.FileField(upload_to=''),
        ),
    ]
