# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 15:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kbs_view', '0006_auto_20170322_0605'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='upload_date',
            field=models.DateField(auto_now=True),
        ),
    ]
